### ISSUE TITLE
using react context with web components

### ISSUE THREAD

**Issue by kopach** [a7ul/react-webcomponentify#12]
@a7ul, do you have any idea how  to update the library in order for it to support react context? 

So, I could do like this:

```js
<custom-component-provider>
 <custom-component-consumer />
</custom-component-provider>
```

Currently, this doesn't work

**Comment by a7ul** [comment]
Yeah this looks like you are trying to render a webcomponent based react context provider ?
dont think this would be easy to support since now this comes out of the react world itself ?

**Comment by a7ul** [comment]
Maybe just use context inside of react itself ? 

Last option would be to looks for regular web alternatives, like a js global variable instead ?

**Comment by a7ul** [comment]
just thinking out loud. 
We could maybe make a custom react hook 
called  `useWebContextProvider` which hooks into a global variable in js and sets that ?

**Comment by kopach** [comment]
I think we can close this issue. I've done some research and I believe this is something which should not be a part of `react-webcomponentify`. In this case, more careful design of React components is required. Basically, depending on use case, there are 2 possible solutions:

1. warp all React components into 1 and then use that as web component 
2. use Redux/Recoil/other mechanism to communicate between React components
