### ISSUE TITLE
react component not unmounted

### ISSUE THREAD

**Issue by WeiRu1016** [a7ul/react-webcomponentify#13]
![image](https://user-images.githubusercontent.com/24243521/127981540-ec887801-42cf-4e7c-bc55-2369216e22f8.png)
没有在卸载的时候调用ReactDOM.unmountComponentAtNode(container) ;不会触发 useEffect 的卸载回调。https://zh-hans.reactjs.org/docs/react-dom.html#unmountcomponentatnode

demo：https://codesandbox.io/s/xenodochial-raman-i9cnj?file=/src/index.js

**Comment by kopach** [comment]
Hi @WeiRu1016, thanks for your report. Fix is merged now. To be released soon

**Comment by a7ul** [comment]
v1.3.2 is released!
