### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by artydev** [a7ul/react-webcomponentify#3]
Hello,

Thanks for this great library.
I would like to functional compoanent with hooks.
Have you an example ?

Regards

Salvatore

**Comment by kopach** [comment]
Hi @artydev, here is live example https://codesandbox.io/s/vibrant-cherry-y72vm?file=/src/App.js:187-569 (based on Official example of `useState` hook: https://reactjs.org/docs/hooks-reference.html#usestate ). See `index.html` for usage of web-component https://codesandbox.io/s/vibrant-cherry-y72vm?file=/public/index.html:1193-1213

**Comment by kopach** [comment]
Closing this issue. Feel free to reopen if something doesn't work for you
