### ISSUE TITLE
Problems with child elements

### ISSUE THREAD

**Issue by ole-treichel** [a7ul/react-webcomponentify#4]
Hey,

First of all: thank you for this library, it think the idea is awesome!

However I cannot make child elements work, like in your demo (the "my-complex-component" example).

I have created a reproduction here: [https://codesandbox.io/s/react-webcomponentify-child-elements-b0j6t?file=/src/Test.js](https://codesandbox.io/s/react-webcomponentify-child-elements-b0j6t?file=/src/Test.js)

Maybe I am just misunderstanding something. Any help would be appreciated!

Cheers

**Comment by kopach** [comment]
that works fine with preact but not with react. Here in this example app `preact` is used and it works https://github.com/a7ul/webcomponents-with-react-webcomponentify/blob/master/package.json
but once you try to replace `preact` with `react` - it fails
